name: Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: wagoid/commitlint-github-action@v5
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: |
                      args: [--strict-peer-dependencies]
            - run: pnpm run lint
            - run: pnpm exec tsc
            - run: pnpm run build-fast
            - run: pnpm run test
