name: NPM / Publish

on:
    workflow_run:
        workflows: ['release-please']
        types: [completed]

jobs:
    test-and-publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
            - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
              with:
                  node-version: 18
            - uses: pnpm/action-setup@v2
              with:
                  version: latest
                  run_install: |
                      args: [--strict-peer-dependencies]
            - run: pnpm run fmt
            - run: pnpm exec tsc --noEmit
            - run: pnpm run build
            - uses: JS-DevTools/npm-publish@5a85faf05d2ade2d5b6682bfe5359915d5159c6c # v2
              with:
                  token: ${{ secrets.NPM_TOKEN }}
                  access: 'public'
